server:
  port: 9003

spring:
  application:
    name: tr-search-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/search}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  elasticsearch:
    connection-timeout: 2s
    socket-timeout: 5s
    host: ${SPRING_ELASTICSEARCH_HOST:localhost}
    port: ${SPRING_ELASTICSEARCH_PORT:9200}
    scheme: ${SPRING_ELASTICSEARCH_SCHEME:http}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs